version: '3.7'

services:
 currency-exchange:
  image: nimbalkar/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
  ports:
   - "8000:8000"
  networks: 
   - currency-network
  depends_on:
   - naming-server
  environment:
   EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
   
 naming-server:
  image: nimbalkar/mmv2-naming-server:0.0.1-SNAPSHOT
  ports:
   - "8761:8761"
  networks: 
   - currency-network
   
networks:
 currency-network: